---
- name: deploy k8scluster
  hosts: k8scluster-master k8scluster-worker
  become: yes
  #serial: 50%
  roles: 
    - { role: common, tags: common }
    - { role: docker, tags: docker }
    - { role: kubeadm, tags: kubeadm }
    - { role: gcloud, tags: gcloud }
