---
# tasks file for kubeadm
- name: set hostname to /etc/hosts
  blockinfile: 
    path: /etc/hosts
    create: yes
    owner: root
    group: root
    mode: 0644
    marker: "# {mark} ANSIBLE MANAGED BLOCK for k8s"
    backup: yes
    block: |
      {{ ansible_eth0.ipv4.address }} {{ inventory_hostname }}
    

- name: stop dphys-swapfile service
  systemd: 
    name: dphys-swapfile.service
    state: stopped
    enabled: no

- name: enable cgroup
  become: yes
  lineinfile: 
    path: /boot/cmdline.txt
    backup: no
    backrefs: yes
    state: present
    regexp: '(.* rootwait)$'
    line: '\1 cgroup_enable=memory cgroup_memory=1'

- name: check init variables
  debug: 
    var: init
  failed_when: init| default('no') == "no"

- name: add gpg-key
  apt_key: 
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: add repo cloud.google.com
  apt_repository: 
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: "present"
    update_cache: yes

- name: install kubeadm
  apt: 
    name: kubeadm
    state: present
    update_cache: yes

- name: include master.yml
  include: master.yml
  when: 
    - k8s_role == "master"

- name: include worker.yml
  include: worker.yml
  when: 
    - k8s_role == "worker"
