# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7
     
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/raspi-k8s-cluster

    steps:
      - checkout

      - run: 
          command: |
            pip install virtualenv
            virtualenv venv

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "./.circleci/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          #- v1-dependencies-

      - run: 
          command: |
            . venv/bin/activate
            pip install -r ./.circleci/requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "./.circleci/requirements.txt" }}

      - run: ansible-lint k8scluster.yml -c .circleci/.ansible-lint -x ANSIBLE0006 -x ANSIBLE0013 -x ANSIBLE0012
      - run: ansible-playbook -i hosts site.yml --syntax-check
